In [1]:
import numpy as np

In [2]:
a1 = np.array([1, 2, 3]) # одномерный массив
a1

array([1, 2, 3])

In [3]:
type(a1) # тип массива

numpy.ndarray

In [4]:
a1.dtype # тип данных элементов массива

dtype('int64')

In [5]:
a1.shape # форма массива

(3,)

In [6]:
a2 = np.array([[1, 2, 3], [4, 5, 6]]) # двумерный массив
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
a2.shape # 2 строки, 3 столбца

(2, 3)

In [8]:
np.arange(0, -1, -0.25) # последовательность чисел из диапазона от 0 до -1 (не включительно) с шагом -0.25

array([ 0.  , -0.25, -0.5 , -0.75])

In [9]:
np.zeros((3, 5)) # двумерный массив из нулей

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.ones((5, 3)) # двумерный массив из единиц

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
np.eye(5) # единичная матрица

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
a1[0] # получение отдельного элемента массива

np.int64(1)

In [13]:
a1[0:3:2] # извлечение подмассива с помощью среза

array([1, 3])

In [14]:
b1 = np.array([10, 20, 30])
b2 = np.array([[11, 22, 33], [44, 55, 66]])

In [15]:
a1 + b1 # поэлементное сложение одномерных массивов

array([11, 22, 33])

In [16]:
a2 + b2 # поэлементное сложение двумерных массивов

array([[12, 24, 36],
       [48, 60, 72]])

In [17]:
a1 * b1 # поэлементное умножение одномерных массивов

array([10, 40, 90])

In [18]:
a2 * b2 # поэлементное умножение двумерных массивов

array([[ 11,  44,  99],
       [176, 275, 396]])

In [19]:
c = np.array([[10, 100, 1000], [20, 200, 2000], [30, 300, 3000]])
c

array([[  10,  100, 1000],
       [  20,  200, 2000],
       [  30,  300, 3000]])

In [20]:
c.sum() # суммирование всех элементов массива

np.int64(6660)

In [21]:
c.min() # минимальный элемент массива

np.int64(10)

In [22]:
c.max() # максимальный элемент массива

np.int64(3000)

In [23]:
c.mean() # среднее значение всех элементов массива

np.float64(740.0)